# Generated by Django 5.0.14 on 2026-05-25 15:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_normalized', models.FloatField(blank=True, null=True)),
                ('unit_normalized', models.CharField(blank=True, default='', max_length=50)),
                ('emission_scope', models.CharField(blank=True, choices=[('scope1', 'Scope 1'), ('scope2', 'Scope 2'), ('scope3', 'Scope 3')], default='', max_length=10)),
                ('source_type', models.CharField(blank=True, default='', max_length=50)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('facility_or_entity', models.CharField(blank=True, default='', max_length=255)),
                ('normalization_log', models.JSONField(default=list)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flag_type', models.CharField(choices=[('MISSING_FIELD', 'Missing Field'), ('INVALID_VALUE', 'Invalid Value'), ('NEGATIVE_VALUE', 'Negative Value'), ('UNSUPPORTED_UNIT', 'Unsupported Unit'), ('INVALID_DATE', 'Invalid Date'), ('DUPLICATE_INVOICE', 'Duplicate Invoice'), ('OVERLAPPING_PERIOD', 'Overlapping Period'), ('INVALID_IATA', 'Invalid IATA Code'), ('CONSUMPTION_SPIKE', 'Consumption Spike'), ('QUANTITY_OUTLIER', 'Quantity Outlier'), ('MISSING_DISTANCE', 'Missing Distance')], max_length=30)),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], max_length=10)),
                ('message', models.TextField()),
                ('field_name', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
