# Generated by Django 5.0.14 on 2026-05-25 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0002_initial'),
        ('pipeline', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='raw_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized', to='ingestion.rawrecord'),
        ),
        migrations.AddField(
            model_name='validationflag',
            name='normalized_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='pipeline.normalizedrecord'),
        ),
    ]
