# Generated by Django 5.0.14 on 2026-05-25 15:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=100)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
    ]
