# Generated by Django 5.0.14 on 2026-05-25 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipeline', '0002_initial'),
        ('review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdecision',
            name='analyst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='normalized_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='pipeline.normalizedrecord'),
        ),
    ]
