# Generated by Django 5.0.14 on 2026-05-25 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='ingested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='ingestion.datasource'),
        ),
        migrations.AddField(
            model_name='rawrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.importbatch'),
        ),
        migrations.AddField(
            model_name='rawrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='tenancy.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='rawrecord',
            unique_together={('batch', 'checksum')},
        ),
    ]
