# Generated by Django 5.0.14 on 2026-05-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={'ordering': ['name']},
        ),
    ]
